# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "CI/CD Pipeline"

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14]
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1 
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simplewhale:latest     
         
      # - name: "Use Node.js ${{ matrix.node-version }}"
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - name: "Cache Node.js modules"
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.OS }}-node-${{ hashFiles('**/package.json') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-node-
      #       ${{ runner.OS }}-
      # - name: "Install application"
      #   run: npm install
      # - name: "Start the Application e2e test"
      #   run: npm run ci 

  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v2
      - name: "Execute smoke test on Docker"
        run: docker-compose -f docker-compose.yml up
  # mongodb:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Check out Git repository"
  #       uses: actions/checkout@v2
  #     - name: "Use Node.js 14"
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #     - name: "Deploy an Instance of MongoDB as a container"
  #       run: docker run -d -p 27017-27019:27017-27019 -v ~/merndb:/data/db --name mernproject mongo:latest  
  # docker-push:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Check out Git repository"
  #       uses: actions/checkout@v2
  #     - name: "Use Node.js 14"
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #     - name: Build and Push Docker Images
  #       uses: mr-smithers-excellent/docker-build-push@v4
  #       with:
  #         image: oren1337/e2e-expensetrack
  #         registry: docker.io
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}  

  notify-slack:
    if: github.event_name == 'push' && (success() || failure())
    needs:
      - docker-test
    runs-on: ubuntu-latest
    steps:
      - name: "Slack workflow notification"
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
